name: Continuous Deployment

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.4.6
        if: github.ref == 'refs/heads/develop'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: learn-qsharp-frontend-stag
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - uses: akhileshns/heroku-deploy@v3.4.6
        if: github.ref == 'refs/heads/master'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: learn-qsharp-frontend-prod
          heroku_email: ${{secrets.HEROKU_EMAIL}}
