name: Continuous Deployment

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push staging
        if: github.ref == 'refs/heads/develop'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push --app learn-qsharp-frontend-stag web

      - name: Build and push production
        if: github.ref == 'refs/heads/master'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push --app learn-qsharp-frontend-prod web

      - name: Deploy staging
        if: github.ref == 'refs/heads/develop'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release --app learn-qsharp-frontend-stag web

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release --app learn-qsharp-frontend-prod web
